### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by christopher-beckham** [amten/NeuralNetwork#2]
Hi there,

Thanks in regards to the previous bug-fix. I've hit another roadblock however, when I install the package and try and run Weka on Mac, I get this:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: weka/classifiers/functions/NeuralNetwork : Unsupported major.minor version 51.0
    java.lang.ClassLoader.defineClass1(Native Method)
    java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    java.security.AccessController.doPrivileged(Native Method)
    java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    java.lang.Class.forName0(Native Method)
    java.lang.Class.forName(Class.java:171)
    weka.core.ClassDiscovery.find(ClassDiscovery.java:343)
    weka.gui.GenericPropertiesCreator.generateOutputProperties(GenericPropertiesCreator.java:528)
    weka.gui.GenericPropertiesCreator.execute(GenericPropertiesCreator.java:620)
    weka.gui.GenericPropertiesCreator.execute(GenericPropertiesCreator.java:596)
    weka.core.converters.ConverterUtils.initialize(ConverterUtils.java:730)
    weka.core.converters.ConverterUtils.<clinit>(ConverterUtils.java:711)
    java.lang.Class.forName0(Native Method)
    java.lang.Class.forName(Class.java:171)
    weka.core.ClassDiscovery.find(ClassDiscovery.java:343)
    weka.gui.GenericPropertiesCreator.generateOutputProperties(GenericPropertiesCreator.java:528)
    weka.gui.GenericPropertiesCreator.execute(GenericPropertiesCreator.java:620)
    weka.gui.GenericPropertiesCreator.<clinit>(GenericPropertiesCreator.java:162)
    weka.core.WekaPackageManager.refreshGOEProperties(WekaPackageManager.java:895)
    weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:889)
    weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:817)
    weka.gui.GenericObjectEditor.determineClasses(GenericObjectEditor.java:174)
    weka.gui.GenericObjectEditor.<clinit>(GenericObjectEditor.java:248)
    weka.gui.GUIChooser.<init>(GUIChooser.java:707)
    weka.gui.GUIChooser.createSingleton(GUIChooser.java:259)
    weka.gui.GUIChooser.main(GUIChooser.java:1558)

    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:171)
    at weka.core.ClassDiscovery.find(ClassDiscovery.java:343)
    at weka.gui.GenericPropertiesCreator.generateOutputProperties(GenericPropertiesCreator.java:528)
    at weka.gui.GenericPropertiesCreator.execute(GenericPropertiesCreator.java:620)
    at weka.gui.GenericPropertiesCreator.execute(GenericPropertiesCreator.java:596)
    at weka.core.converters.ConverterUtils.initialize(ConverterUtils.java:730)
    at weka.core.converters.ConverterUtils.<clinit>(ConverterUtils.java:711)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:171)
    at weka.core.ClassDiscovery.find(ClassDiscovery.java:343)
    at weka.gui.GenericPropertiesCreator.generateOutputProperties(GenericPropertiesCreator.java:528)
    at weka.gui.GenericPropertiesCreator.execute(GenericPropertiesCreator.java:620)
    at weka.gui.GenericPropertiesCreator.<clinit>(GenericPropertiesCreator.java:162)
    at weka.core.WekaPackageManager.refreshGOEProperties(WekaPackageManager.java:895)
    at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:889)
    at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:817)
    at weka.gui.GenericObjectEditor.determineClasses(GenericObjectEditor.java:174)
    at weka.gui.GenericObjectEditor.<clinit>(GenericObjectEditor.java:248)
    at weka.gui.GUIChooser.<init>(GUIChooser.java:707)
    at weka.gui.GUIChooser.createSingleton(GUIChooser.java:259)
    at weka.gui.GUIChooser.main(GUIChooser.java:1558)

```

The weka.jar I use is the exact same one I use on Windows, and there are no issues on Windows.

I'm assuming I'll have to recompile your Java files on Mac and Linux to get it working? Let me know what you think.

**EDIT** - I checked the Java version on the machines that worked (and the ones that didn't as well) and I think it might be related to the version. It seems to crap out on 1.6 but it works on 1.7. If this is the case, then I'll have to either re-compile your code using JDK 1.7 or I'll have to add Java 1.7 to my classpath.

**EDIT2** - yes using Java 1.7 solved the issue. Feel free to close this ticket, or whatever. :)

Cheers :)

**Comment by amten** [comment]
:)  Yep, that error is due to an older version of java being used than what the classes are compiled for. Thanks for reporting AND solving :) !

**Comment by Floryndas** [comment]
Hello, I have the same issue but my java version is 1.7, so i don't understand what is the problem. 
Can you just tell me what's the matter?
ps: I'm using weka 3.6.10-2. In other to be more precisely, this is the error i have:
$ weka
[warning] /usr/bin/weka: Unable to locate libsvm.jar in /usr/share/java
Exception in thread "main" java.lang.UnsupportedClassVersionError: weka/gui/GUIChooser : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by mik3hall** [comment]
On Apr 16, 2015, at 9:18 PM, Floryndas notifications@github.com wrote:

> Hello, I have the same issue but my java version is 1.7, so i don't understand what is the problem. 

I notice there doesn’t seem to be a build included with the distribution. From a distribution directory that includes source something like this works for me on OS X…

javac -source 1.7 -target 1.7 -d classes -cp lib/BLAS-dlls.zip:lib/mtj-1.0-snapshot.jar:lib/opencsv-2.3.jar:lib/weka.jar src/amten/ml/_.java src/amten/ml/matrix/_.java src/amten/ml/examples/_.java src/amten/ml/test/_.java src/weka/classifiers/functions/*.java

change to 
-source 1.6 -target 1.6
if you really prefer that and it’s compatible with the source itself, that is gets no errors in compilation.

Then something like...
jar -cvf NeuralNetwork.jar -C classes/ . 

Michael Hall

**Comment by puneetjindal** [comment]
@Floryndas : Any resolution on this. I am facing the following error on this
information.gain(Response~., mydata)
Error in .jnew("weka/core/Attribute", attname[i], .jcast(levels, "java/util/List")) : 
  java.lang.UnsupportedClassVersionError: weka/core/Attribute : Unsupported major.minor version 51.0

**Comment by Floryndas** [comment]
@puneetjindal : hello, have you try the proposal of Michael Hall?
@mik3hall : have try that solution on ubuntu, please?
